# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
# Stonecutter chiseled builds + Loom don't play well with parallel execution.
org.gradle.parallel=false
org.gradle.configuration-cache=false

# Mod Properties (shared across all versions)
mod_version=1.9.0
maven_group=io.github.keoz5
archives_base_name=zombiezcompanionV2
